apply plugin: 'com.android.library'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

android {
    namespace "pl.hackyeah.sygnet.listen"
    compileSdk getProperty("unity.compileSdkVersion") as int
    buildToolsVersion getProperty("unity.buildToolsVersion")

    compileOptions {
        // sic: Unity zapisuje tę właściwość z literówką („Compatability”)
        sourceCompatibility JavaVersion.valueOf(getProperty("unity.javaCompatabilityVersion"))
        targetCompatibility JavaVersion.valueOf(getProperty("unity.javaCompatabilityVersion"))
    }

    defaultConfig {
        minSdk getProperty("unity.minSdkVersion") as int
        targetSdk getProperty("unity.targetSdkVersion") as int
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
